name = "pulse-server"
compatibility_date = "2025-01-25"
main = "src/index.ts"

assets = { directory = "assets" }

[durable_objects]
bindings = [{name = "PULSE_SERVER", class_name = "PulseServer"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["PulseServer"]

#[site]
#bucket = "./assets"

